# Site settings
name: Lucas Tang
email: lctang@iastate.edu
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Security Automation"
skills: "Software Engineering Student in Ames, IA"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: github
    url: https://github.com/Ltango
    


    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 78AB46
  primary-rgb: "33, 150, 243"
  secondary: 458B00
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
